dawnhud.toggler=Включен
dawnhud.upper_toggler=Верхние индикаторы
dawnhud.lower_toggler=Нижние индикаторы
dawnhud.sound_normal=Звук стандартного урона
dawnhud.sound_strong=Звук сильного урона
dawnhud.max_inds=Макс-е кол-во индикаторов (для верхних и нижних)
dawnhud.lifetime=Время исчезновения (в секундах)
dawnhud.upper_picker=Цвет верхних индикаторов (без прозрачности)
dawnhud.lower_picker=Цвет нижних индикаторов (без прозрачности)