dawnhud.toggler=Enabled
dawnhud.upper_toggler=Upper indicators
dawnhud.lower_toggler=Lower indicators
dawnhud.sound_normal=Standart damage sound
dawnhud.sound_strong=Strong damage sound
dawnhud.max_inds=Max indicators amount (both lower and upper)
dawnhud.lifetime=Indicator lifetime (in seconds)
dawnhud.upper_picker=Upper indicators color
dawnhud.lower_picker=Lower indicators color